/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2022.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

/* ** ** ** ** ** * AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! * ** ** ** ** ** */

package com.bh.at.tester;

import static com.bh.at.apiutil.CyAPIUtilFactory.apif;
import static com.bh.at.main.AppConfig.*;

import com.bh.at.iapiutil.IAPIHelper;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import org.junit.Assert;

public final class CreateRiskTester {
  public static Consumer<String> testRunnerLogger;
  private IAPIHelper createRISKApiHelper;
  private final Map<String, Object> metaInfo = new HashMap<>();
  private final Map<String, IAPIHelper> apiHelpers = new HashMap<>();
  private String lastApiFileUsed;
  public CreateRiskTester() {
  }
  /**
   * the api file CCUS.CreateRISK:apiJSON.
   *
   * @param apiFile The file, which contains the api definitions.
   */
  public void initCreateRISKApi(String apiFile) {
    createRISKApiHelper = getApiHelper(apiPaths, apiFile);
    log2TestRunner("\n>>>>> createRISK : Function initCreateRISKApi (the api file CCUS.CreateRISK:apiJSON) not fully implemented.");
  }
  /**
   * the user calls delete:CreateRISK:apiCALL.
   *
   * @param apiCall The REST api call that is to be invoked.
   */
  public void callDeleteCreateRISKApi(String apiCall) {
    metaInfo.clear();
    metaInfo.put("cyborg:reqName", apiCall);
    System.out.println(createRISKApiHelper.getApiJsono(metaInfo));
    Assert.assertTrue(apiCall + " from file " + lastApiFileUsed + " failed.", createRISKApiHelper.callAPI(metaInfo));
    log2TestRunner("\n>>>>> createRISK : Function callDeleteCreateRISKApi (the user calls delete:CreateRISK:apiCALL) not fully implemented.");
  }
  /**
   * user should get success response with status code 204.
   *
   * @param p0
   */
  public void createRISK_f1(Integer p0) {
    log2TestRunner("\n>>>>> createRISK : Function createRISK_f1 (user should get success response with status code 204) not fully implemented.");
    System.out.println(createRISKApiHelper.getActRespBody());
    Assert.assertEquals("400",createRISKApiHelper.getActRespCode() );
  }
  /**
   * user should get bad request response with status code 400.
   *
   * @param p0
   */
  public void createRISK_f2(Integer p0) {
    log2TestRunner("\n>>>>> createRISK : Function createRISK_f2 (user should get bad request response with status code 400) not fully implemented.");
  }

  /**
   * Locate the api file from the list of folders specified by apiPaths
   * and associate it with the apiHelper object.
   * The lastApiFileUsed used is used to track the last api file referenced, this is useful
   * when the api call and api file are not a part of the same step definition.
   *
   * @param   apiFilePaths  The json array specifying the locations in order, where the apiFile can be found.
   * @param   apiFile   The apiFile that is associated with the apiHelper object.
   * @return apiHelper The object associated with the api file.
   */
  private IAPIHelper getApiHelper(List<String> apiFilePaths, String apiFile) {
    lastApiFileUsed = apiFile;
    IAPIHelper apiHelper;
    String key = apiFilePaths.toString() + apiFile;
    if (apiHelpers.containsKey(key)) {
      apiHelper = apiHelpers.get(key);
    } else {
      apiHelper = apif.getAPIHelper(apiFilePaths, apiFile, proxyUrl, proxyPort, ignoreSSL);
      apiHelpers.put(key, apiHelper);
    }
    return apiHelper;
  }

  /**
   * Add log messages to cucumber report.
   *
   * @param msg The message to be logged.
   */
  private void log2TestRunner(String msg) {
    testRunnerLogger.accept(msg);
  }
}
