# Autogenerated feature file CCUS.CreateRISK.feature
@CCUS_APP_API_TEST1
Feature: Risk Register API Feature
@Test
  Scenario: Verify that user is able to successfully create a risk using createRisk API
    Given the api file "CCUS_CreateRisk_Success:apiJSON"
    When the user calls "post:CreateRISK:apiCALL"
    Then user should get success response with status code 201
  @Test
  Scenario: Verify that user is able to successfully delete a risk using deleteRisk API
    Given the api file "CCUS_DeleteRisk_Success:apiJSON"
    When the user calls "delete:CreateRISK:apiCALL"
    Then user should get success response with status code 204

  @Test
  Scenario:  Verify that application throws error when input body is incorrect for createRisk API
    Given the api file "CCUS_CreateRisk_BadRequest:apiJSON"
    When the user calls "post:CreateRISK:apiCALL"
    Then user should get bad request response with status code 400

  @Test
 Scenario: Verify that application throws error when input body is incorrect for deleteRisk API
    Given the api file "CCUS_DeleteRisk_BadRequest:apiJSON"
    When the user calls "delete:CreateRISK:apiCALL"
    Then user should get bad request response with status code 400
