# Autogenerated feature file CCUS.CreateRISK.feature
@CCUS_APP_API_TEST1
Feature: CreateRISK of project CCUS

  Scenario: Verify that user is able to successfully delete a risk using deleteRisk API successfully
    Given the api file "CCUS_CreateRISK:apiJSON"
    When the user calls "delete:CreateRISK:apiCALL"
    Then user should get success response with status code 204

 Scenario: Verify that application throws error when input body is incorrect for deleteRisk API
    Given the api file "CCUS_CreateRISK_BadRequest:apiJSON"
    When the user calls "delete:CreateRISK:apiCALL"
    Then user should get bad request response with status code 400
